Initial Commit
danmons/retronas-dist pull request #1
Opened 2022-03-19 05:10 UTC by munderwoods

Took out simple-cdd and changed username to pi

2022-03-20 19:15 UTC, munderwoods commented
- docker is redundant now
- some missing setup info if you want to stay with Docker
- debian subfolder
- sudoers changes
- remove redundant sudo group change
- debian mirror redirector dl
- output artifact perms

2022-03-21 23:04 UTC, sairuk requested changes
Looks good overall, please see inline notes

2022-03-21 23:04 UTC, sairuk commented on README.md
> +The Makefile just runs the bash scripts in the repo with different arguments depending on what you want to do. Different distributions are split up into their own directories.
remove the word `just`

2022-03-21 23:04 UTC, sairuk commented on README.md
> +After the ISO is downloaded, the build command is run for the specified architecture. The iso iss unpacked into a temporary directory called isofiles. The file "preseed.cfg" is then injected into tha
typo `iss`

2022-03-21 23:04 UTC, sairuk commented on README.md
> +The directory "isofiles" is then packed back up into a new RetroNAS image that you can boot.
remove `back up` ... `packed into` is fine

2022-03-22 21:53 UTC, sairuk commented on README.md
> +6. Open the DEBIAN_VERSION file and change it to whatever version you'd like.
make init is no longer valid

2022-03-22 22:04 UTC, sairuk commented on README.md
> +8. Run the make command for the architecture you desire (example: "make build-amd64") or "make build-all" to build for all architectures.
this is now called `build-debian-amd64`

2022-03-23 02:17 UTC, munderwoods commented on Makefile
> +make-dists: ## Make the directory where the preseeded distrobution images will end up
Then why they always call them distros?

2022-03-23 02:51 UTC, munderwoods commented on debian/preseed.cfg
> +d-i passwd/username string pi
Yeah lemme know what you wanna do about that whenever you're ready.

2022-03-23 03:31 UTC, sairuk commented on Makefile
> +make-dists: ## Make the directory where the preseeded distrobution images will end up
that is a question for the larger linux community, correct spelling is `distribution`

2022-03-23 03:32 UTC, merged