Initial rpios setup
danmons/retronas-dist pull request #7
Opened 2022-04-09 21:42 UTC by munderwoods

I'd like to see if this works for you guys. It got a little complicated and so I started looking into this project as well: https://github.com/Nature40/pimod/

Let me know what you guys think.

2022-04-09 21:43 UTC, munderwoods commented
The builds will fail since I changed the name of the make targets to be better organized with different dists. 

Mainly I wanna see if this builds OK for you guys. I haven't tested the resultant image yet, I'll do that shortly.

2022-04-09 21:48 UTC, munderwoods commented
Alright, I booted it up and retronas is installed. I obviously just run the install script here with no other configuration so let me know if there's anything else you need done.

2022-09-01 21:08 UTC, sairuk commented on rpios/build.sh
> +#!/bin/bash
this has two int lines, clean this up

2022-09-01 21:29 UTC, sairuk requested changes
See comments, please also add a github workflow to build the loop mounted rpi image for testing against

2022-09-01 21:29 UTC, sairuk commented on Makefile
> +	cd rpios && docker build -t retronas:packer .
is this still required? don't we just loop mount now?

2025-07-25 06:23 UTC, merged